volumes:
  redis:

services:
  redis:
    image: redis:latest
    command: /bin/sh -c "redis-server --requirepass test_password"
    volumes:
      - redis:/var/lib/redis/data
    ports:
      - 6379:6379